kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name  es
      Match *
      Host  <your opensearch domain>
      Port  443
      AWS_Auth On
      AWS_Region  <your region>
      tls On
      Index fargate_log
      Type  _doc
